### ISSUE TITLE
mimiciii.cohort_modify

### ISSUE THREAD

**Issue by LandAndLand** [Sophiaaaaaa/AKI-Prediction#1]
may I ask where can i get mimiciii.cohort_modify?I download mimiciii dataset ,but i didn't found any table which is named  cohort_modify

**Comment by sreered** [comment]
@LandAndLand in the data folder in this git repo there is a RaR file with both cohorts https://github.com/Sophiaaaaaa/AKI-Prediction/blob/master/data/data_set.rar

Download this and unzip and you can load this into postgres

But I couldnt find code on how they generated cohort in first place. I will ask a question regarding that.

**Comment by LandAndLand** [comment]
Dear Sophiaaaaaa：

I had read your article "Precisely Predicting Acute Kidney Injury with Convolutional Neural Network Based on Electronic Health Record Data"&nbsp;&nbsp;and the source code carefully . I thought there was a problem with information leakage of your model during the training (I have no experience and please forgive me if I misunderstand), so I revised the training and testing&nbsp;process.The result of AUC test is less than 98.8%. Your paper is well written. Please check the small problems to avoid the flaws of your paper.

Best Wishes!

Yours 

LinShan Hou

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sophiaaaaaa/AKI-Prediction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 上午6:55
收件人:&nbsp;"Sophiaaaaaa/AKI-Prediction"<AKI-Prediction@noreply.github.com&gt;;
抄送:&nbsp;"候琳珊"<1138578898@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sophiaaaaaa/AKI-Prediction] mimiciii.cohort_modify (#1)





 
@LandAndLand in the data folder in this git repo there is a RaR file with both cohorts https://github.com/Sophiaaaaaa/AKI-Prediction/blob/master/data/data_set.rar
 
Download this and unzip and you can load this into postgres
 
But I couldnt find code on how they generated cohort in first place. I will ask a question regarding that.

**Comment by Sophiaaaaaa** [comment]
> may I ask where can i get mimiciii.cohort_modify?I download mimiciii dataset ,but i didn't found any table which is named cohort_modify

Thanks for your question. The TABLE named 'mimiciii.cohort_modify' is not the original TABLE from MIMIC-III dataset, but the processed TABLE using SQL scripts in this work. Because of the RULES of using MIMIC-III dataset, we haven't upload the SQL scripts yet.

**Comment by Sophiaaaaaa** [comment]
> @LandAndLand in the data folder in this git repo there is a RaR file with both cohorts https://github.com/Sophiaaaaaa/AKI-Prediction/blob/master/data/data_set.rar
> 
> Download this and unzip and you can load this into postgres
> 
> But I couldnt find code on how they generated cohort in first place. I will ask a question regarding that.

Sorry for replying late. We haven't upload the SQL scripts yet because of the RULES of using MIMIC-III dataset.
